### ISSUE TITLE
补充一个用邮箱推送的单文件改版

### ISSUE THREAD

**Issue by ilhmtfmlt2** [BoltLv4215/huluxia_thirdfloor_signin#2]
[Au_Hlx.zip](https://github.com/user-attachments/files/17867780/Au_Hlx.zip)

**Comment by BoltLv4215** [comment]
✨ 感谢您的分享！未来我会认真考虑将其融入主分支中 🚀。如果您有空闲，非常欢迎提交 PR（Pull Requests）贡献更多精彩内容 🌟！
